### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by Lewiscowles1986** [AndrewCarterUK/CryptoKey#1]
Why this vs just using the dep paragonie/random_compat ?

**Comment by AndrewCarterUK** [comment]
`paragonie/random_compat` is a library and not a command line tool, so it isn't an alternative. This tool uses that library but provides a command line interface on top.

The actual alternative to this tool is the OpenSSL command line utility. I've documented this alternative in the README (including instructions on how to use it) and recommended its use if available.

To answer the more general 'Why?' question - because I recently contacted two separate library authors regarding concerns over the entropy of the cryptographic keys used in their project examples and documentation.

The main purpose of the README for this repository is to provide clear instructions on how to generate secure keys for cryptographic purposes. I'll accept any pull requests or advice that helps accomplish this :)

The ability for it to be bundled with other PHP projects is secondary, but something I still feel is important.

I'll close this issue as I believe that I have now answered the question asked. If you have a response to what I've said here then I will reopen this. If you have any further questions they will probably be better suited to a new issue.
